import './globals.css'
import { Kalam } from 'next/font/google'

const kalam = Kalam({
  weight: ["300","400","700"], subsets: ['latin-ext']
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={kalam.className}>{children}</body>
    </html>
  )
}
